name: Send notification on pull-request

on: [pull_request]

jobs: 

  pr:
    runs-on: ubuntu-latest

    steps:
      - name: Init
        uses: actions/checkout@v2

      - name: Send Discord notification for new pull-request
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_DEVELOP }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'Nouvelle pull-request sur le repo {{ EVENT_PAYLOAD.pull_request.head.repo.full_name }} par {{ EVENT_PAYLOAD.pull_request.user.login }} | message: {{ EVENT_PAYLOAD.pull_request.body }}'

      