name: Push changes on pull-request

on: pull_request

jobs: 

  pr:
    if: github.event.pull_request.head.repo.full_name == github.repository

    runs-on: ubuntu-latest

    steps:
      - name: Init
        uses: actions/checkout@v2

      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --local user.email "antoinemaurel6@gmail.com"
          git config --local user.name "anmaurel"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit -m "PR changes"
          git push

      