name: Test and deploy app

on:
  push:
    branches: [master]

jobs:

  tests:
    strategy:
      matrix:
        node-version: [12.x, 13.x]
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Init
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install & build
        run: |
          npm install
          npm run build
        env:
          CI: true
      
      - name: Send SMS for successful test
        uses: nexmo-community/nexmo-sms-action@master
        env:
          NEXMO_API_KEY: ${{ secrets.NEXMO_API_KEY }}
          NEXMO_API_SECRET: ${{ secrets.NEXMO_API_SECRET }}
        with:
          nexmoNumber: ${{ secrets.NEXMO_NUMBER }}
          recipientNumber: 33608130305
          message: "Successful test on ${{ github.repository }} from ${{ github.actor }}"

  deploy:
    needs: [tests]

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd sites/iim
            if [ ! -d "devops-anmaurel"]
            then
              git clone https://github.com/IIM-Creative-Technology/devops-anmaurel.git
            else
              git pull origin master
            fi
            cd devops-anmaurel
