name: Test and deploy app

on:
  push:
    branches: [develop]

jobs:
  tests:
    strategy:
      matrix:
        node-version: [12.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Init
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install and test
        run: |
          npm install
          npm run build
        env:
          CI: true

  deploy:
    needs: [tests]

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd anmaurel_devops
            git pull origin master
