name: Deploy app

on:
  push:
    branches:
      - master

jobs:
  deploy:

    runs-on: ubuntu-latest

    # strategy:
    #   matrix:
    #     node-version: [12.x]

    steps:
      - name: Init project
        uses: actions/checkout@v2

      # - name: Init nodejs
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: ${{ matrix.node-version }}

      # - name: Installing project dependencies
      #   run: npm install
      
      # - name: Building the project
      #   run: npm run build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          # buildpack: "https://github.com/heroku/heroku-buildpack-nodejs.git"
          # procfile: "web: heroku-nodejs dist/"