name: Deploy app

on:
  push:
    branches:
      - develop

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Init project
        uses: actions/checkout@v2

      - name: Lauch container
        run: docker-compose up -d

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.5.7
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          appdir: "./client"
          usedocker: true