name: Test and deploy on pre-production server

on:
  push:
    branches: [preprod]

jobs:

  pre-deploy:
    strategy:
      matrix:
        node-version: [12.x, 13.x]
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Init
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install & build
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: Test
        run: |
          npm run test
      
      - name: Commit depedencies & built files
        run: |
          git config --local user.email "antoinemaurel6@gmail.com"
          git config --local user.name "anmaurel"
          git checkout -b deploy
          git add -f dist/
          git add -f node_modules/
          git commit -m "Build dependencies now because server don't support nodejs"
          git push -f origin deploy

  deploy:
    needs: [pre-deploy]

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd sites/iim/devops-anmaurel
            git pull --all
            git checkout preprod
            git merge origin/deploy
            git branch -d deploy
            git push origin :deploy

  feedback:
    needs: [deploy]

    runs-on: ubuntu-latest

    steps:
      - name: Send Discord notification for successful deploy on preprod
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_PREPROD }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed on pre-production server'