name: Test and deploy on production server

on:
  push:
    branches: [master]

jobs:

  pre-deploy:
    strategy:
      matrix:
        node-version: [12.x]
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Init
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install & build
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GIT_TOKEN }}
          eslint: true
          prettier: true
          auto_fix: true
          git_name: ${{ github.actor }}
          commit_name: "Fix code style before push prod with ${linter}"
      
      - name: Test
        run: |
          npm run test
      
      - name: Commit depedencies & built files
        run: |
          git config --local user.email "antoinemaurel6@gmail.com"
          git config --local user.name "anmaurel"
          git checkout -b deploy
          git add -f dist/
          git add -f node_modules/
          git commit -m "Build dependencies now because server don't support nodejs"
          git push -f origin deploy

  deploy:
    needs: [pre-deploy]

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd sites/iim/devops-anmaurel
            git pull --all
            git checkout master
            git merge origin/deploy
            git branch -d deploy
            git push origin :deploy
  
  feedback:
    needs: [deploy]

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        width: [1200, 600]

    runs-on: ubuntu-latest

    steps:
      - name: Screenshot website to have a quick overview 
        uses: swinton/screenshot-website@v1.x
        with:
          source: http://iim.antoine-maurel.com/
          destination: screenshot-${{ matrix.os }}-${{ matrix.width }}.png
          width: ${{ matrix.width }}
          full-page: true

      - name: Send Discord notification for successful deploy on prod
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_PROD }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The project {{ EVENT_PAYLOAD.repository.full_name }} has been deployed on production server'

      - name: Send SMS for successful deploy on prod
        uses: nexmo-community/nexmo-sms-action@master
        env:
          NEXMO_API_KEY: ${{ secrets.NEXMO_API_KEY }}
          NEXMO_API_SECRET: ${{ secrets.NEXMO_API_SECRET }}
        with:
          nexmoNumber: ${{ secrets.NEXMO_NUMBER }}
          recipientNumber: 33608130305
          message: "Successful deploy on ${{ github.repository }} from ${{ github.actor }}"
