name: Test and deploy on production server

on:
  push:
    branches: [master]

jobs:

  tests:
    strategy:
      matrix:
        node-version: [12.x, 13.x]
        os: [ubuntu-latest]
    
    runs-on: ${{ matrix.os }}

    steps:
      - name: Init
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install & build
        run: |
          npm install
          npm run build
        env:
          CI: true

      - name: Commit built files
        run: |
          git config --local user.email "antoinemaurel6@gmail.com"
          git config --local user.name "anmaurel"
          git checkout -b deploy
          git add -f dist/
          git add -f node_modules/
          git commit -m "Build dependencies because server don't support nodejs"
          git push -f origin deploy

  deploy:
    needs: [tests]

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd sites/iim/devops-anmaurel
            git pull origin master
  
  feedback:
    needs: [deploy]

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ubuntu-latest

    steps:
      - name: Send SMS for successful deploy
        uses: nexmo-community/nexmo-sms-action@master
        env:
          NEXMO_API_KEY: ${{ secrets.NEXMO_API_KEY }}
          NEXMO_API_SECRET: ${{ secrets.NEXMO_API_SECRET }}
        with:
          nexmoNumber: ${{ secrets.NEXMO_NUMBER }}
          recipientNumber: 33608130305
          message: "Successful deploy on ${{ github.repository }} from ${{ github.actor }}"

      - name: Screenshot Website
        uses: swinton/screenshot-website@v1.x
        with:
          source: http://antoine-maurel.com/
          destination: screenshot-${{ matrix.os }}.png
          full-page: true
